// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdRsNXWrU5-5aQ1qmhaDJtkZvEVlxluT4',
    appId: '1:1097774478630:web:57b4397684066bba53bde7',
    messagingSenderId: '1097774478630',
    projectId: 'fiesta-9c7f4',
    authDomain: 'fiesta-9c7f4.firebaseapp.com',
    storageBucket: 'fiesta-9c7f4.firebasestorage.app',
    measurementId: 'G-X1KKENJNCV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDSUlU75846Eqf5NJ5LRWw2jhMS1TsaX8',
    appId: '1:1097774478630:android:5f4df77b6d5ee9e953bde7',
    messagingSenderId: '1097774478630',
    projectId: 'fiesta-9c7f4',
    storageBucket: 'fiesta-9c7f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYb-xsrIgpjtnINAXmEnyfyn4CSWEPUnM',
    appId: '1:1097774478630:ios:7c14ff4403bf13d453bde7',
    messagingSenderId: '1097774478630',
    projectId: 'fiesta-9c7f4',
    storageBucket: 'fiesta-9c7f4.firebasestorage.app',
    iosBundleId: 'com.example.fiesta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYb-xsrIgpjtnINAXmEnyfyn4CSWEPUnM',
    appId: '1:1097774478630:ios:7c14ff4403bf13d453bde7',
    messagingSenderId: '1097774478630',
    projectId: 'fiesta-9c7f4',
    storageBucket: 'fiesta-9c7f4.firebasestorage.app',
    iosBundleId: 'com.example.fiesta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdRsNXWrU5-5aQ1qmhaDJtkZvEVlxluT4',
    appId: '1:1097774478630:web:784693dc1e8760c453bde7',
    messagingSenderId: '1097774478630',
    projectId: 'fiesta-9c7f4',
    authDomain: 'fiesta-9c7f4.firebaseapp.com',
    storageBucket: 'fiesta-9c7f4.firebasestorage.app',
    measurementId: 'G-JZ2PPS3FDL',
  );

}